### PR TITLE
Allow changing calendar when editing event

### LINKED ISSUE #141: Feature request: moving events between calendars
See [moving events between calendars](https://github.com/etesync/server/issues/49)

### PR DESCRIPTION
**Pull request by ramzan**
Fixes #141 and partially #138, which also requests a default calendar option.

### CODE REVIEW

**Comment by tasn** [comment]
I'm on the fence about this change. I wonder if it's better to have a "move to another collection" option that will be available for contacts, calendars and tasks instead of transparently deleting and adding to another collection. The most obvious way where it's matter is the change history which is lost - so users need to at least be aware of this.

**Comment by tasn** [comment]
Btw, I don't know if you saw the `etebase` branch, but that's the etesync 2.0 branch that cleaned up a lot of the code! I'll probably have it ready for testing later this week so maybe consider starting developing there from then on.

**Comment by ramzan** [comment]
Yeah that seems like a better idea. I'll close this PR and check out `etebase`.

**Comment by tasn** [comment]
Just FYI: I haven't ported over all of your PRs yet.

**Pull request closed without merging**
