### PR TITLE
Email does not have to always be email (in case of selfhosted etesync)

### PR DESCRIPTION
**Pull request by nemanjan00**

### CODE REVIEW

**Comment by tasn** [comment]
Hey,

Thanks for the patch, but unfortunately this fix can't go in as is. There are benefits to having the field as "email", and in the case of the hosted etesync version, it must be email. I think a better approach here would be to have it as "email" by default, and change it to "text" if the user clicked on "advance".

Please update the PR, and I'll merge it.

Thanks,
Tom.

**Comment by nemanjan00** [comment]
Ok, will take a look at it tomorrow :D

**Comment by tasn** [comment]
Oh, and please also change the related title from "email" to "username" (again, only in the advanced case).

**Comment by tasn** [comment]
Hey, just following up on this one. :)

**Comment by nemanjan00** [comment]
Sorry, I am busy atm. I am not in a hurry to fix this, but, I do plan to...

**Comment by tasn** [comment]
Hey, just following up on this one. Any progress? Do you still plan on fixing this? If not, please let me know and I'll take a jab.

Thanks!

**Comment by nemanjan00** [comment]
I do plan, but, I am quite busy. 

I can not do it right now. If you are not in a hurry to fix it, you can wait for me.

**Comment by tasn** [comment]
I'll give you a bit more time. No rush. I'm just keen to fix it because it prevents people from using etesync-web when they self-host etesync.

**Comment by tasn** [comment]
Sorry, I had some spare time for low-hanging fruits and decided to fix this.

I made you a co-author (github is aware of that too, take a look at the commit).

**Comment by nemanjan00** [comment]
Well, thanks! :D

**Pull request closed without merging**
