### PR TITLE
Clicking a task goes directly to edit page

### PR DESCRIPTION
**Pull request by AbleLincoln**
Changes the user flow so that selecting a task bypasses the "Task view" and goes directly to the edit page.

### CODE REVIEW

**Comment by tasn** [comment]
Looks good to me, just one comment, could you make the commit messages conform to the rest of the commit messages? I know there's no style guideline at the moment (I should make one!) but you can see from existing messages. E.g. for this one, I'd make it: "Tasks: change clicking on task to go directly to edit page."

**Comment by AbleLincoln** [comment]
Yeah whoops, I kind of messed that up haha. Give me a sec, I can fix

**Comment by tasn** [comment]
Cool. :)
Another cool git tool in case you are unfamiliar with it is: `git rebase -i` which lets you edit history. So you can for example, in this case run `git rebase -i HEAD~4` which will let you squash together the last few commits, reorder them, reword them and whatever.

**Comment by AbleLincoln** [comment]
Does this work?

**Comment by tasn** [comment]
Yup, good job! Sorry again for all of the hassle, but there's quite a bit of code involved and quite a few commits, so I'd rather we do things right from the start, even with these small changes. :)

**Pull request merged**
