### PR TITLE
Contacts: Add basic group editing functionality

### PR DESCRIPTION
**Pull request by ramzan**
The basic functionality requested in #136 is here: creating/editing/deleting groups and adding/removing members.

 The UI still needs some work, but this should work for now.

### CODE REVIEW

**Comment by tasn** [comment]
Oh wow, you are quick, good job!
I like what you did with adding `contact` and `group` to the URL, seems like the good approach. Why didn't you do it for edit too? How are groups edited then? Just directly from the contacts field?

My main comment is: why have them both in ContactEdit? Why not have ContactEdit and GroupEdit as separate views (You can even redirect between them if you get the wrong type)? They don't seem to be sharing much code anyway, and it's similar to how we split the rest of the views.

Looking forward to hearing your thoughts..

**Comment by ramzan** [comment]
I agree with all your comments. The reason I stuffed everything into ContactEdit is that I was preoccupied with figuring it out/making it work and forgot about good design lol. I'll split it into separate views, no problem.

**Comment by tasn** [comment]
Hehe, looking forward to the next version! :)

**Comment by ramzan** [comment]
Should be good now

**Comment by tasn** [comment]
Sorry it took me a few days to review, I wanted to give it a proper look, though everything is great, gj!

**Pull request merged**
